spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            filters: stat,wall,log4j
            initial-size: 5
            maxActive: 20
            maxPoolPreparedStatementPerConnectionSize: 20
            maxWait: 60000
            min-idle: 5
            minEvictableIdleTimeMillis: 300000
            poolPreparedStatements: true
            stat-view-servlet:
                allow: 127.0.0.1,192.168.163.1
                deny: 192.168.1.73
                login-password: 123456
                login-username: admin
                reset-enable: false
                url-pattern: /druid/*
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            validationQuery: SELECT 1 FROM DUAL
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
                url-pattern: /*
        password: Cui!2345
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://82.156.68.175:3306/ManagementSystemDemo?useSSL=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show-sql: true